### ISSUE TITLE
Enforce trailers

### ISSUE THREAD

**Issue by mristin** [mristin/opinionated-commit-message#78]
The `signed-off-by`  is not the only trailer which can be expected in a message. For a complete list, see: https://git.wiki.kernel.org/index.php/CommitMessageConventions

Please let me know on this issue if you need the enforcement of other trailers and discuss how it should be implemented.

**Comment by nhhagen** [comment]
Is it possible to "reverse" the implementation so that the user provides the patterns of the trailers they wan't to verify?

It could be implemented with either regex or simpler starts with logic.

Eg:

```yaml
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v2
        with:
          trailers:
            - Reported-by:
            - Signed-off-by:
            - Resolves: #\d+
            - See also:
```
